# DataSource Config category,comment,post,user,user_action,user_collection,user_message
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:mysql://localhost:3308/forum
    username: root
    password: password
  freemarker:
    settings:
      classic_compatible: true
      datetime_format: yyyy-MM-dd HH:mm
      number_format: 0.##
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml